### ISSUE TITLE
New entry.

### ISSUE THREAD

**Issue by ohbob** [tr1ckydev/great.db#1]
How would you add an entry to the db, with out reading your db - i.e. not knowing the last id? The examples don't make sense.

**Comment by tr1ckydev** [comment]
I understand your concern, what you are telling about is an autoincrementing feature which would increment the id by 1 every time a new record is inserted without needing to know the last id.

This is a very early project hence many features are missing as of now. **I have planned to add this feature** and a lot more things in my next release which is coming soon :)

And as for the examples, they are pretty generic just demonstrating how it's done because there are different use cases like a discord bot database where userId would be the key which is unique from each other.

**Comment by bugs181** [comment]
One solution would be to do this in your project (OOB) if you need this feature. You could do this with a `Set` and keep adding the IDs to it, and check the count when you need a new one.

**Comment by tr1ckydev** [comment]
@bugs181 Appreciate the suggestion, but I don't think it's needed because SQLite already has a AUTOINCREMENT feature which exactly does the job and I would just need to implement it.

What I have come up with is that, a new schema type will be introduced like "autoincrement" which makes the column automatically increment id whenever new data is inserted.

**Comment by bugs181** [comment]
@tr1ckydev apologies. I'm fairly unfamiliar with SQL. Looking forward to `AUTOINCREMENT`.
